

import Footer from "./componentes/Footer/page"

export const metadata = {
  title: 'Create App User',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
      <body>{children}
      <div>
      <Footer/>
      </div>
      
      </body>
      
    </html>

    
  )
}
