import Header from "./Header/page"
import styles from "../../public/assets/header.module.css"




export const metadata = {
  title: 'Create App User',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Header/>
      <body>
        <div>
      <h1 className={styles.header}>Steevanz</h1>
        {children}

        </div>
      
      </body>
      
    </html>

    
  )
}
