

import Footer from "./componentes/Footer/page"

import { ChakraProvider } from '@chakra-ui/react'


export const metadata = {
  title: 'Create App User',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
      <body>{children}</body>
      
    </html>

    
  )
}
